itapira/enquete/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:questao_id>', views.detalhe, name="detalhe"),
    path('<int:questao_id>/resultados', views.resultados, name="resultados"),
    path('<int:questao_id>/voto/', views.voto, name="voto")
]

itapira/itapira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("enquete/", include('enquete.urls')),
    path('admin/', admin.site.urls),
]

itapira/enquete/models.py
from django.db import models


# Create your models here.
# Conterá as tabelas da aplicação.

class Questao(models.Model):
    pergunta = models.CharField(max_length=200)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.pergunta} - {self.data}"


class Resposta(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    resposta = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.questao.pergunta}? - {self.resposta}"

itapira/enquete/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from .models import Questao


# Create your views here.
def index(request):
    ultimas_questoes = Questao.objects.order_by("-data")  # [:4]
    context = {"ultimas_questoes": ultimas_questoes}
    return render(request, "enquete/index.html", context)


def loucura(request):
    return HttpResponse("E nessa loucura.....")


def detalhe(request, questao_id):
    # try:
    #     questao = Questao.objects.get(pk=questao_id)
    # except Questao.DoesNotExist:
    #     raise Http404("Questão non ecxisty")
    # get_object_or_404 tenta fazer um select e retorna automaticamente 404 se não houver elementos
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, "enquete/questao.html", {'questao': questao})


def resultados(request, questao_id):
    return HttpResponse("voce esta olhando o resultado da questao %s" % questao_id)


def voto(request, questao_id):
    return HttpResponse("voce esta votando na questao %s" % questao_id)

itapira/enquete/templates/enquete/index.html
{# Comentário no template do Django #}
{# Verifica se a variável ultimas_questoes tem conteúdo #}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
</head>
<body>
{% if ultimas_questoes %}
    <div class="container">
        <h1>Minhas questões</h1>
        <ul class="list-group">
            {# Faz um for sobre as questoes dentro da variável #}
            {% for questoes in ultimas_questoes %}
                <li class="list-group-item">
                    {# retorna o id da questao {{questoes.id}} #}
                    {# utiliza o name da url para pegar ela #}
                    <a href="{% url 'detalhe' questoes.id %}">{{ questoes.pergunta }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    {# Se a variável ultimas_questoes for vazia... #}
{% else %}
    <p>Não há questões salvas</p>
{% endif %}
</body>
</html>

itapira/enquete/templates/enquete/questao.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="mt-4 p-5 bg-primary text-white rounded">
                <h1>Pergunta do Dia</h1>
            </div>
            <p class="fs-3">{{ questao.pergunta }}</p>
            <p>Publicado em {{ questao.data }}</p>

            <ul>
                {% for respostas in questao.resposta_set.all %}
                    <li>{{ respostas.resposta }} - votos: {{ respostas.votos }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
</body>
</html>